apiVersion: apps/v1
kind: Deployment
metadata:
  name: main
  namespace: prova
spec:
  replicas: 3
  selector:
    matchLabels:
      app: main
  template:
    metadata:
      labels:
        app: main
    spec:
      containers:
      - name: meu-container
        image: mattewz300/main
        ports:
        - containerPort: 8000