apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: main-hpa
  namespace: prova
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: main  # Substitua pelo nome do seu Deployment
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50